# Generated by Django 3.2.6 on 2021-11-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dorm', models.CharField(max_length=200)),
                ('home', models.CharField(max_length=200)),
            ],
        ),
    ]
